// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// sass_compile_string_rcpp
int sass_compile_string_rcpp(std::string string, std::string outfile, int output_style, int precision);
RcppExport SEXP _libsassr_sass_compile_string_rcpp(SEXP stringSEXP, SEXP outfileSEXP, SEXP output_styleSEXP, SEXP precisionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type string(stringSEXP);
    Rcpp::traits::input_parameter< std::string >::type outfile(outfileSEXP);
    Rcpp::traits::input_parameter< int >::type output_style(output_styleSEXP);
    Rcpp::traits::input_parameter< int >::type precision(precisionSEXP);
    rcpp_result_gen = Rcpp::wrap(sass_compile_string_rcpp(string, outfile, output_style, precision));
    return rcpp_result_gen;
END_RCPP
}
// sass_compile_file_rcpp
int sass_compile_file_rcpp(std::string filename, std::string outfile, int output_style, int precision);
RcppExport SEXP _libsassr_sass_compile_file_rcpp(SEXP filenameSEXP, SEXP outfileSEXP, SEXP output_styleSEXP, SEXP precisionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type filename(filenameSEXP);
    Rcpp::traits::input_parameter< std::string >::type outfile(outfileSEXP);
    Rcpp::traits::input_parameter< int >::type output_style(output_styleSEXP);
    Rcpp::traits::input_parameter< int >::type precision(precisionSEXP);
    rcpp_result_gen = Rcpp::wrap(sass_compile_file_rcpp(filename, outfile, output_style, precision));
    return rcpp_result_gen;
END_RCPP
}
// version
std::string version();
RcppExport SEXP _libsassr_version() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(version());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_libsassr_sass_compile_string_rcpp", (DL_FUNC) &_libsassr_sass_compile_string_rcpp, 4},
    {"_libsassr_sass_compile_file_rcpp", (DL_FUNC) &_libsassr_sass_compile_file_rcpp, 4},
    {"_libsassr_version", (DL_FUNC) &_libsassr_version, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_libsassr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
