// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// sass_compile_string
int sass_compile_string(std::string str);
RcppExport SEXP _libsassr_sass_compile_string(SEXP strSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type str(strSEXP);
    rcpp_result_gen = Rcpp::wrap(sass_compile_string(str));
    return rcpp_result_gen;
END_RCPP
}
// version
std::string version();
RcppExport SEXP _libsassr_version() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(version());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_libsassr_sass_compile_string", (DL_FUNC) &_libsassr_sass_compile_string, 1},
    {"_libsassr_version", (DL_FUNC) &_libsassr_version, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_libsassr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
