# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sass_compile_string <- function(str) {
    .Call(`_libsassr_sass_compile_string`, str)
}

version <- function() {
    .Call(`_libsassr_version`)
}

