# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sass_compile_string <- function(str, output_style = 0L, precision = 5L, source_comments = FALSE, is_indented_syntax_src = FALSE, source_map_contents = FALSE, source_map_embed = FALSE, omit_source_map_url = TRUE) {
    .Call(`_libsassr_sass_compile_string`, str, output_style, precision, source_comments, is_indented_syntax_src, source_map_contents, source_map_embed, omit_source_map_url)
}

sass_compile_file <- function(filename) {
    invisible(.Call(`_libsassr_sass_compile_file`, filename))
}

version <- function() {
    .Call(`_libsassr_version`)
}

