# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sass_compile_string_rcpp <- function(string, outfile, output_style, precision) {
    .Call(`_libsassr_sass_compile_string_rcpp`, string, outfile, output_style, precision)
}

sass_compile_file_rcpp <- function(filename, outfile = "", output_style = 0L, precision = 5L) {
    .Call(`_libsassr_sass_compile_file_rcpp`, filename, outfile, output_style, precision)
}

version <- function() {
    .Call(`_libsassr_version`)
}

